version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb+srv://nisarg09:Nisarg%4009@cluster0.2hfg7.mongodb.net/ems_db?retryWrites=true&w=majority
      - JWT_SECRET=93aB^x$E76oPp!fL02mW@zQ4%
      - TOKEN_EXPIRES_IN=1h

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
